name: Commit build

on:
  workflow_call:
    outputs:
      version:
        description: "Version"
        value: ${{ jobs.build.outputs.version }}

# Abort the build if there are newer changes.
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  build:
    name: Commit build
    runs-on: ubuntu-latest
    outputs:
      version: "1.0.${{github.run_number}}"
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world! I built and published packages...
        
  deploy-dev:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{needs.build.outputs.version}}
      environment: dev
