name: Deploy

on:
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        type: string
      environment:
        description: "Environment name"
        required: true
        type: string
        
jobs: 
  deploy:
    name: "Deploy ${{inputs.version}}/${{inputs.environment}}"
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploying..."
        
